input.onButtonPressed(Button.A, function () {
    led.stopAnimation()
    basic.showNumber(input.runningTime())
    music.setVolume(255)
    music.changeTempoBy(50)
    for (let index = 0; index < 1; index++) {
        music.playTone(247, music.beat(BeatFraction.Whole))
        music.playTone(330, music.beat(BeatFraction.Whole))
        music.playTone(330, music.beat(BeatFraction.Half))
        music.playTone(392, music.beat(BeatFraction.Half))
        music.playTone(370, music.beat(BeatFraction.Whole))
        music.playTone(330, music.beat(BeatFraction.Double))
        music.playTone(494, music.beat(BeatFraction.Whole))
        music.playTone(440, music.beat(BeatFraction.Double))
        music.playTone(440, music.beat(BeatFraction.Whole))
        music.playTone(370, music.beat(BeatFraction.Double))
        music.playTone(370, music.beat(BeatFraction.Whole))
        music.playTone(330, music.beat(BeatFraction.Whole))
        music.playTone(330, music.beat(BeatFraction.Half))
        music.playTone(392, music.beat(BeatFraction.Half))
        music.playTone(370, music.beat(BeatFraction.Whole))
        music.playTone(311, music.beat(BeatFraction.Whole))
        music.playTone(311, music.beat(BeatFraction.Whole))
        music.playTone(349, music.beat(BeatFraction.Whole))
        music.playTone(247, music.beat(BeatFraction.Double))
        music.playTone(247, music.beat(BeatFraction.Whole))
        music.playTone(330, music.beat(BeatFraction.Whole))
        music.playTone(330, music.beat(BeatFraction.Half))
        music.playTone(392, music.beat(BeatFraction.Half))
        music.playTone(370, music.beat(BeatFraction.Whole))
        music.playTone(330, music.beat(BeatFraction.Double))
        music.playTone(494, music.beat(BeatFraction.Whole))
        music.playTone(587, music.beat(BeatFraction.Double))
        music.playTone(554, music.beat(BeatFraction.Whole))
        music.playTone(523, music.beat(BeatFraction.Double))
        music.playTone(415, music.beat(BeatFraction.Whole))
        music.playTone(523, music.beat(BeatFraction.Whole))
        music.playTone(523, music.beat(BeatFraction.Half))
        music.playTone(494, music.beat(BeatFraction.Half))
        music.playTone(466, music.beat(BeatFraction.Whole))
        music.playTone(233, music.beat(BeatFraction.Double))
        music.playTone(392, music.beat(BeatFraction.Whole))
        music.playTone(330, music.beat(BeatFraction.Double))
    }
})
input.onButtonPressed(Button.B, function () {
    music.setVolume(255)
    music.setTempo(400)
    for (let index = 0; index < 1e+25; index++) {
        music.playSoundEffect(music.createSoundEffect(WaveShape.Sine, 5000, 5000, 255, 255, 9999, SoundExpressionEffect.None, InterpolationCurve.Linear), SoundExpressionPlayMode.UntilDone)
    }
})
input.onGesture(Gesture.Shake, function () {
    basic.showNumber(3)
    control.waitMicros(1)
    basic.showNumber(2)
    control.waitMicros(1)
    basic.showNumber(1)
    control.waitMicros(0)
    basic.clearScreen()
})
